### ISSUE TITLE
Seeing bad requests on the skill endpoints

### ISSUE THREAD

**Issue by Ofekw** [dend/grunt#3]
Specifically, any of the skill endpoints `https://skill.svc.halowaypoint.com` returns a 400 response. Any ideas? 
`https://halostats.svc.halowaypoint.com:443` work fine.

Exact response: 
```
{StatusCode: 400, ReasonPhrase: 'Invalid player ids list', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Server: Microsoft-HTTPAPI/2.0
  Strict-Transport-Security: max-age=157680000; includeSubDomains
  X-Content-Type-Options: nosniff
  E2EActivity: eNyxyrJvbU+dMb3P4+wKmQ==
  Date: Sat, 16 Apr 2022 04:22:12 GMT
  Content-Length: 0
}}
```

**Comment by Ofekw** [comment]
Looking at the network traffic I was able to repro the issue - the APIS requires a header in this format e.g.
`players:xuid({playerId});` I was passing along the xuid to SkillGetMatchPlayerResult but the code doesn't wrap the id in `xuid({id})` hence the confusion. 

![image](https://user-images.githubusercontent.com/7378811/163664045-3a78b3be-3f60-435f-9405-c561ef691e93.png)

The SkillGetMatchResult doesn't work at all and returns a 400 with the above response. 

I'll add a PR tomorrow to wrap strings properly and support an XboxTicket for extracting the xuid rather than doing it manually each time.

**Comment by dend** [comment]
Reopening this so that I can investigate @Ofekw

**Comment by dend** [comment]
Did some more digging here, and noticed that for some matches I indeed get `HTTP/1.1 400 Invalid player ids list`. To mitigate this, I am implementing a change by which you need to pass a list of XUIDs to be investigated.

**Comment by dend** [comment]
This should be documented and resolved in the latest set of commits - thanks again for the issue, @Ofekw!
